# Generated by Django 4.1.6 on 2023-02-14 09:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_straits_times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.RemoveField(
            model_name='story',
            name='genre',
        ),
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.ManyToManyField(to='old_straits_times.genre'),
        ),
    ]
