# Generated by Django 4.1.6 on 2023-02-15 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_straits_times', '0002_alter_story_content_remove_story_genre_story_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='last_update_date',
            new_name='date_last_updated',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='published_date',
            new_name='date_published',
        ),
        migrations.AddField(
            model_name='story',
            name='views_in_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='views_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='abstract',
            field=models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
