# Generated by Django 4.1.6 on 2023-02-16 08:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('old_straits_times', '0005_author_bio_author_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
