# Generated by Django 4.1.6 on 2023-02-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_straits_times', '0006_alter_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='social1',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='author',
            name='social2',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='author',
            name='social3',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='author',
            name='social4',
            field=models.CharField(default='', max_length=120),
        ),
    ]
