# Generated by Django 4.1.6 on 2023-02-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_straits_times', '0010_alter_comment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.CharField(default='', max_length=40),
        ),
    ]
