# Generated by Django 4.1.6 on 2023-02-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('old_straits_times', '0011_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='image',
            new_name='avatar',
        ),
    ]
