# Generated by Django 4.1.6 on 2023-02-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_straits_times', '0012_rename_image_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='public/user_avatars'),
        ),
    ]
