# Generated by Django 4.1.6 on 2023-02-22 03:44

from django.db import migrations
import django_resized.forms
import old_straits_times.models


class Migration(migrations.Migration):

    dependencies = [
        ('old_straits_times', '0017_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatars/none/default.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[150, 150], upload_to=old_straits_times.models.PathAndRename('/avatars')),
        ),
    ]
