# Generated by Django 4.1.6 on 2023-02-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_straits_times', '0019_alter_author_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='views_in_week',
        ),
        migrations.AddField(
            model_name='story',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
