# Generated by Django 4.1.6 on 2023-02-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_straits_times', '0020_remove_story_views_in_week_story_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.ManyToManyField(blank=True, to='old_straits_times.genre'),
        ),
    ]
